
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // DATABASE_URL: transaction pooler (port 6543) — app runtime, phù hợp
    // serverless (Vercel). DIRECT_URL: session pooler (port 5432) — dùng
    // riêng cho `prisma migrate` (transaction pooler không hỗ trợ schema
    // migration). Supabase: Project Settings -> Database -> Connect.
    url: env("DATABASE_URL"),
    directUrl: env("DIRECT_URL"),
  },
});
